name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install
        working-directory: src

      - name: Build website
        run: npm run build
        working-directory: src

      - name: Deploy to GitHub Pages
        run: |
          mkdir public
          mv src/html/* public/
        working-directory: public

      - name: Commit and Push Changes
        run: |
          git config --local user.email "sauravvirat7156508@gmail.com"
          git config --local user.name "Saurav"
          git add .
          git commit -m "Deploy website to GitHub Pages"
          git push

